baseURL: "https://fissssssh.com/"
languageCode: en-us
title: fissssssh
theme: PaperMod
menu:
  main:
    - identifier: posts
      name: 文章
      url: /posts/
      weight: 1
    - identifier: misc
      name: 杂项
      url: /categories/misc/
      weight: 2
taxonomies:
  category: categories
  tag: tags
